<blockquote class="blockquote-center leave-message">快来留言吧！~请在 <a href="https://github.com/aak1247/aak1247.github.io/issues/1" target="_blank">Github issue</a> 页面完成操作_(:з」∠)_</blockquote>
<div id="messages">
    <div id="gh-comments-info">
            <a href="javascript:void(0);">
            <span id="ghComments-count">0</span>条留言</a>
    </div>
    <ul id="gh-comments" style="opacity: 1"></ul>
</div>
<script src="https://cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript" src="{{ url_for(theme.js) }}/src/issue.js"></script>